name: Daily Stocks Scanner

on:
  schedule:
    - cron: "0 6 * * *"   # כל יום ב-06:00
    - cron: "0 14 * * *"  # כל יום ב-14:00
  workflow_dispatch:

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          pip install yfinance python-telegram-bot==13.15

      - name: Run Stocks Bot
        run: python stocks_bot.py
        env:
          TOKEN_STOCKS: ${{ secrets.TOKEN_STOCKS }}
          CHAT_ID: ${{ secrets.CHAT_ID }}
